index.html
Implemented key indicators when using keyboard to navigate and select colours. Hides when not in use.
=> Implemented keybind indicators & hiding

index.html, style.css
=> Implemented a server "online" CSS indicator

.gitignore, CNAME, server.js
Didn't know that this was an important file lol
=> Re-add CNAME

index.html
screw ads they breaking everythniunghytrmythnyrnyrebb
=> Remove ad ifrane

index.html
We do a little trolling (this should maybe be undone, but the channels UI needs to stay)
=> Initial channels UI and discord invite trolling

index.html
Super rushed mega update to add farsi channel due to sudden influx of users speaking this language.
=> Farsi channel and additional channel support

index.html
AMINBGUSBfvourhiupbeobepipjpeijnpenpepnie
(mental breakdown moment)
=> Right to left name format in persian channel

index.html
Null fixes and temp UI div removal
=> Fixes and ui bug rever

index.html, style.css
Load simple art previews to help build pixelart with the overlay tool!
SHIFT+S to open server menu
SHIFT+O to open overlay menu
=> Implemented official site overlay

index.html
Fixes being able to write anything onthe overlay's inputs
=> Overlay input fix

index.html, style.css
I really condensed that translation code as well, well done me!
=> Live chat tooltip animations and translations

index.html, style.css
=> Overlay menu and server switch menu tooltips

index.html
The very cute fin emoji is the first one to be implemented (Thanks FlinFlanFinFan)
=> Implemented custom live chat emojis

index.html, style.css
Context menu with the features to mention and block a user.
=> Live chat right click context menu

index.html
Prevent botting with extreme measures
=> censor iframes, delete createElement

index.html
=> Trollpost changes

index.html, server.js, style.css
This will probably be implemented serverside on new rplace server, current server is deprecated as far as I am concerned
=> Live server palette sharing + code cleanup

index.html, manifest.json, style.css
It looks good enough for now, hopefully this will encourage more people to use site as a progressive web app
=> Make site prompt to install as PWA

index.html, manifest.json
=> Try fix manifest

style.css, sw.js
Hopefully chrome will say yes now....
=> Implement fetch patch to PWA SW

index.html, style.css
Original implementation was rushed, with many inline styles and no real positioning, much improved version is more concise, uses less BR hacks, and should provide better UX
=> Improve captcha modal display on small portrait devices

index.html, style.css
Make captcha buttons a little larger on desktop, remove pesky margins
=>  Desktop captcha button touchup size 

index.html
Should make site more scalable, and a few optimisations here and there will negate any filesize increases
=> Big main code refactor + New server integration

index.html
Switch to new protocol that should be more performant, less janky, and just better
=> Unjank and upgrade captcha to new server protocol

index.html
This was certainly one of the bugs
=> YAY! Fix mobile button input bug

index.html
Fix canvselect alignment and drag
=> Fix canvselect

index.html
- Credits to @StarlkYT for arabic translations
=> Add japanese, hindi and arabic translations

index.html, style.css
Fixes some dodgy old code, and cleans up many broken UI elements/broken animations to prepare us for some later big updates
=> Multiple site UI fixes and code cleanups

index.html, style.css
Place chat can be deemed asa annoying during raids, or could contain unwanted content, so this PR attempts to make them disableable
=> Simple disable place chat

404.html, index.html, instance.html, style.css
Megacommit containing all clientside code for the new experiemntal custom canvases / server instances feature, includes fixes for scrolling chat on mobile and other bugs and related issues on the site
=> [MASSIVE] Merge custom canvases, mobile patches and cooldown fixes

index.html
If on mobile, the last colour you placed will now persist when you open the palette again in order to reduce finger strain. On desktop, such functionality does not occur and the experience stays authentic to reddit's r/place event.
=> Fix persistent colours + mobile only

index.html
Overlays now come with the canvas they are located on, and the game will automatically move to the overlay position so it is clearly visible
=> Cleanups and overlay fixes

index.html
POV: You remove useless element ids and end up breaking something (html moment)
=> Fix overlay slider value

index.html
I might have a programming addiction. What am I even adding at this point.
https://github.com/rslashplace2/rslashplace2.github.io/assets/73035340/b099986c-971b-440e-8616-5651f096091a
=> Display custom emoji previews, nicer chat commands

index.html, server.js
Also prevented vip key from being leaked in chat due to missing return and tidied up server code into a switch statement
=> Uid based kick/ban functionality and mod packet

.gitignore, index.html, server.js
Moderation should be much better now. More control over live chat cooldown, etc and general site wide fixes.
=> Moderation fixes, live chat cooldown mutes and server cleanups

index.html, style.css
Just want to test this in hopes of having baseder more creative ads on the site!
=> Backport nicer ad covering & bonzi ad

db-worker.js, index.html, server.js
last nitpick before we are likely ready for main merge
=> Small DB and packet fixes

db-worker.js, index.html, migration-04-11-23.sh, server.js, style.css
Schema changes -> Migration as of 04/11/23 adds the UserVips, LiveChatDeletions tables and deletionId column to LiveChatMessages. Use the `migration-04-11-23.sh` shell script to upgrade.
=> Moderator actions overhaul, VIP and Livechat DB improvements

index.html, server.js, style.css
WIP - Should be fine for now but many features are questionable or somewhat broken. Investigate fixes.
=> Clientside punishment fixes, clearer server punish info

.eslintrc.json, index.html, server.js
Can I just say this is a behemoth
=> Single session VIP keys. Diff based VIP key watch. Server code cleans and bug fixes

server.js
=> Fix incorrect VIP close code

elements.js, index.html, rplace-2023.css, style.css
HTML custom elements my beloved, gobbless modern web
=> Refactor out icon close into cuustom elem, noad 14 day limit

index.html
I corrected some typos and added some translations for "My account"
anyways, thats all... wehehehe
=> Corrected typos + Added translations

index.html
=> Test code to block laptop touchpad zooming

index.html
We have farmed enough views, it is officially milked dry
=> Remove timelapse ad popup

server.ts
JSDoc has served us well, but it is time to delve into the deep end...
Bun can be dodgy, and having an even more dodgy server on top is bad, downsides are basically zero since bun commands to run js and ts are identical and the only major difference will be better IDE support
=> Typescript server test (safety fixes) + blacklist updates

server.ts
Turns out  you  can't  spread an object to extend it...
Alternate solution (more typescript-y)
https://www.reddit.com/r/typescript/comments/rjxdsn/comment/hp7qfiv/?utm_source=share&utm_medium=web2x&context=3
=> Fix empty server object

db-worker.ts, index.html
Captcha, live chat delete and  punish packets should operate as expected  now
=> [OOF] Fix broken  toQueryObject and gnarly client switch case overruns

db-worker.ts, server.ts
This  one method has caused so many problems it is insane
=> Announce all channels, live chat delete final fix

index.html
Small bugfix for clientside packet reading
=> Fix clientside read

server.ts
Pixels should be rejected with the appropriate rejection packet, etc more frequently now
=> Cleanup pixel packet returns, nicer rejection handling

index.html
- :whoplaced chat command will allow  you to see details  of whoever placed pixel at current location,
- chat system will also try to detect a VIP key leak and prevent it if it is attempted to send in chat
=> Whoplaced chat command

index.html
=> Fix captcha buttons no value

index.html, rplace-2022.css, rplace-2023.css, style.css
Browsers may load captcha images very slowly
=> Captcha options button loading spinner

darkplace.js, index.html, rplace-2022.css, rplace-2023.css, style.css, svg/loading-spinner.svg
=> Darkplace april 1st event

darkplace.js, index.html, rplace-2022.css, rplace-2023.css, style.css
Browser decided to be stupid and some weirdness was preventing styleElement and intermediate from removing from dom properly. Now theme func is even more bloated, and theme transitions are likely broken, but eh, that is the least of the concern atm
=> Add back darkplace as a theme, add dark mode theme

darkplace.js, index.html, rplace-2022.css
So it turns out the document.documentElement node has some insane hidden functionality where by changing any main attribute on it, it seems to cause an entire document reparse, resulting in all event listeners being wiped, elemnt references to be broken and generally the entire site to be borked. Who would have guessed?!?!??!! Anyway, this doesn't apply when using dataset-, so we do that now
#ilovewebdev #webisperfectlybalancedwithnoexploits #js2024 #web3.0
=> YEAHHAHHHH - Resolve theme intermediate issue and themes effects API

.gitignore, index.html, server.ts
Probably one of the most extreme anti bot measures in response to rapid raids, will carry out increasing levels of mitigating actions depending on severity to try and stop quick surges in pixel placements. Canvas lock also finally separated out officially to packet code 8
=> Implement PXPS_SECURITY module

server.ts
Blob literally had a morbillion years to fix this. Oh well, at least the code is readable now
=>  Revert to legacy run length coding algorithm 

index.html, server.ts, style.css
*"How many anti bot measures are you gonna implement?"* They said
*As many as I need to... Zekiah replied*
=>  Implement cloudflare turnstile captcha 

captcha-canvas.js, index.html, style.css
Annoying that this needs to  be implemented but it seems at least a few clients are on really old mobile devices which necessitate this. Interesting to learn!
=> Captcha popup no-webgl canvas2d patch

db-worker.ts
I would test code on my local machine, but I can't even get bun to run without a segfault :brain: 
#bunlove #fastestjsruntime #newthingalwaysequalsgood
=> Hotfix db worker SQL typos

server.ts
=> Hotfix db worker report message

db-worker.ts
=> Database report insert fix

server.ts
Bug while testing discovered changes was still using the old size after a dimensions update. Should be fixed now
=> Fix new changes size

.gitignore, index.html, package.json, server.ts
Adds connection shadowban, also should improve game security in some scenarios + nicer report and general cleanups
=> Remove table report format, modlog file & client activity packet

server.ts
=> Make previous similar checks work on place chat & short msg edgecases

index.html, server.ts
Fix linkage packet code (150 -> 110)
- Note to self: Packet codes that work with TextEncoder/TextDecoder must be under 128 to encode to single UTF-8 codepoint
this was pure skill issue
=> Fix linkage packet code

index.html
Index used should now be valid, with some extra cleanups and removal of dirty HTML interoplation
=> Refactor generate palette & PEN logic to work with palette usable regions

index.html, server.ts
Silly mistake - Forgot to implement  serverside instance ID
=> Hotfix serverside encoding  of linkage packet

index.html
Every big update comes with a lot of small hotfixes
=> Hotfix accideental multiple response comsumption in content upload

index.html, style.css
Making it clearer that a post is being submitted to the user, disabling inputs to prevent spam while it uploads, giving an abbreviated status as the upload occurs and various other UX fixes
=> Upload contents in parallel, add progress status, post uploading UX

elements.js, index.html, posts-manager.js, rplace-2022.css, style.css
I honestly thought I had already merged these  but it  went to the wrong branch.. damn git
=>  Fix bug in loadTopPosts iteration, formalise #main, .title and .description styles for community posts & fixes

index.html, posts.html, shared.js
=>  Make DEFAULT_AUTH a shared resource 

index.html, posts.html, style.css
Causing weird wrapping on chrome
=> Fix bad text wrapping in posts

index.html, posts.html
I really really really really really really really really really really really really really really really really really hate browser caching
=> Bump shared.js

posts.html, server.ts
- Fix keyword search patch is already merged
=> Blacklist info, VIP enforce user chat name, turnstile fix, names fixes + chatname cooldown

index.html
- Chat should scroll to appear to maintain position when message input height is changed, along with fixes to generally make it less  clunky
- Also a small fix to make  window message handler ignore cloudflare messages
=> Update message input height on send + message input height change chat scroll

elements.js, index.html, posts.html, style.css
Thanks @pastasales on the discord for spotting the bug here
=> Post validation updatees, fix post rules dialog bug and better post content handling

fakeapp.html, index.html, posts.html, style.css
Looks sooo much better now, also includes user Id, which will help staff be able to track down a ban (until server API exposes ban Id)
=> Clientside punishment handling fixes and dedicated punishment panel

censors.txt
This file is going to have the most unhinged regexes ever seen soon
=> Add even more cases to censors

censors.txt, server.ts
Extract from my big brain thesis:
> if you ever have a chat filtering system, the best way to reduce people attempting to bypass it / cursing is actually to censor the message for everyone except the sender
> If you censor it for the sender, they will likely go and try send whatever they wanted to say again and again until they find some variation that bypasses the filter
=> Bump cennsors file, censor message for all clients except sender (psyop)

server.ts
This should make bans and mutes much more effective against a user who is punished, connecting to the game on a new IP that was not previously in the KnownIps of the user, but who had forgotten to also clear their cookies  with their user ID, allowing us to also go and ban that too. Also the bans /  mutes packet finally make use of the intId as they should
~~Hopefully there are no new security holes~~
=> Cleanup bans/mutes handling, virally infect new IPs with same user ID

404.html, fakeapp.html, instance.html
Most other changes are whitespace/tab related
=> Fully re-implement 404, and canvas vanity check, validation and code cleanups

404.html, elements.js, index.html, posts-manager.js, posts.html, shared.js
Hopefully we do not end up with over 1K requests when scrolling two the bottom of posts now!
~~at least after the first time~~
=> TranslateAll on post page, implement idexedDb posts auth profiles & users caching

index.html
Cursed, but isn't being cursed kinda the point of JS. Like ofc we can't have nice things.  Anyway, this should fix things
=> Fix muted and place chat default values w/ rolling update hack

index.html, live-chat-elements.js, shared-elements.js, style.css
Should optimise the amount of elements per chat message, fixes weird chat history loading errors & better cleans up reaction handling logic
=> Chat hisstory hotfix, refine live chat reactions styles & top level singleton emoji panel component

src/index.js
Includes handleNameInfo IPC handler, should address some issues with missing chat names on the clientside.
=> Handle intIdNames on client & display #{intId} format instead of 'Unknown' when chat name not found

src/index.js
Remove some of the boolean hell for cooldown handling, make place button and keybind activation of palette menu more reliable and general logic improvements
=> Attempt to improve & cleanup Websocket state and Cooldown handling

src/index.js
Futher clarifications and minor edge case fixes for Cooldown state
=> Further bolstering of Cooldown state handling

ads.txt, index.html, posts.html
The small google ads experiment concluded that google ads is infaesible for rplace.live, will be shortly demoing ezoic to better figure out what fits the site best.
=> Remove google ads references, and demo ezoic experiment

index.html, posts.html, src/pages/index/index.js, styles.css
Cooldown should now be more accurately calculated, reducing the chance of cooldown violations or false positives, in accordance with server upgrades to better ensure cooldown calculation stability, historical live chat messages should once again be interactive, and able to be reacted to / replied to, minor bugs regarding z-indexes of UI elements have been fixed
=> Improve cooldown handling, prediction and accuracy, fix chat panel historical message interactivity, Z ordering & bug fixes

index.html, posts.css, premium.css, public/css/rplace-2022.css, public/css/rplace-2023.css, src/defaults.js, src/pages/index/effects/darkplace.js, src/pages/index/effects/snowplace.js, src/pages/index/game-themes.js, src/pages/index/index.js, src/shared-elements.js, src/shared.js, styles.css
This PR introduces several improvements and refactors across the theme and UI systems:
- Theme handling refactored to a new dedicated themes module, with minor bugfixes concerning theme and effecs loading
- Dynamic effects module loading added, enabling reinstatement of special effects such as darkplace and snowplace.
- Context menu updates, including:
- Style tweaks for better visual consistency
- Accessibility enhancements
- Minor interaction improvements
- Minor code tweaks and easier-to-access secret settings menu
=> Refactor theme handling, re-add effects support & UI and accessibility fixes

index.html, public/css/rplace-2022.css, public/css/rplace-2023.css, src/pages/index/advanced-view-menu.js, src/pages/index/board-renderer-3d.js, src/pages/index/board-renderer.js, src/pages/index/board-selections.js, src/pages/index/viewport.js, styles.css, tests/board-renderer-test.html, tests/board-renderer-test.js
More progress on bringing the selections system to reality with current selections integration, with the current selection being hilighted as it is modified, AVM selections logic has been refactored into a BoardSelections class as well as multiple selections related bug fixes and improvements.
Update also includes minor style fixes across the board, the largest of which being reddit orange being adopted as the default accent colour across the 2022 and 2023 theme
=> Add 2022/2023 themed selection handles, AVM selections display, current selections & BoardSelections class

bun.lock, index.html, package.json, public/css/rplace-2022.css, public/css/rplace-2023.css, src/pages/index/game-state.js, src/pages/index/game-themes.js, src/pages/index/hcaptcha-dialog.js, src/pages/index/index.js, src/pages/index/viewport.js, src/shared.js, styles.css
- Updated message handlers for more encapsulation and consistency 
- Implemented hCaptcha support within toast captcha display
- Internal updates along serverside fixes to improve site stability and security
- Minor UI adjustments for name input button padding
Consider moving hcaptcha and turnstile toast menus to work as a dialog, so that other inputs can be blocked while the captchas are being completed to reduce bounced server actions
=> Minor toast and name input CSS improvements, code refactors & hCaptcha support
